const fs = require("fs");
const path = require("path");

const manifestPath = path.join(__dirname, "manifest.json");
const swVersionPath = path.join(__dirname, "sw-version.js");

// Project configurations are now managed in the app via the database.
// The manifest no longer lists project files; it only carries the build
// timestamp used to version the service-worker cache.
const manifest = {
  buildTime: Date.now(),
  projects: [],
};

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

const cacheFiles = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js",
];

const swVersionSource = `// Auto-generated by build.js — do not edit
const CACHE_VERSION = "${manifest.buildTime}";
const CACHE_FILES = ${JSON.stringify(cacheFiles, null, 2)};
`;

fs.writeFileSync(swVersionPath, swVersionSource);

console.log("Generated manifest.json (projects are now configured in-app, not via text files)");
console.log("Generated sw-version.js (cache version: " + manifest.buildTime + ")");
