const fs = require("fs");
const path = require("path");

const projectDir = path.join(__dirname, "Projects");
const manifestPath = path.join(__dirname, "manifest.json");
const swVersionPath = path.join(__dirname, "sw-version.js");

if (!fs.existsSync(projectDir)) {
  throw new Error("Projects directory not found: " + projectDir);
}

const files = fs
  .readdirSync(projectDir)
  .filter((file) => file.toLowerCase().endsWith(".txt"))
  .sort((a, b) => a.localeCompare(b));

const projects = files.map((file) => {
  const name = path.basename(file, path.extname(file));
  const id = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return {
    id,
    name,
    file: "Projects/" + file,
  };
});

const manifest = {
  buildTime: Date.now(),
  projects,
};

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

const cacheFiles = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js",
  ...projects.map((project) => "./" + project.file),
];

const swVersionSource = `// Auto-generated by build.js — do not edit
const CACHE_VERSION = "${manifest.buildTime}";
const CACHE_FILES = ${JSON.stringify(cacheFiles, null, 2)};
`;

fs.writeFileSync(swVersionPath, swVersionSource);

console.log("Generated manifest.json with " + projects.length + " project(s):");
projects.forEach((project) => {
  console.log("  " + project.name + " (" + project.file + ")");
});
console.log("Generated sw-version.js (cache version: " + manifest.buildTime + ")");
