-- Run this in your Supabase SQL editor AFTER running supabase-setup.sql.
--
-- Creates a separate table to store one long text description per task.
-- Task IDs are string keys generated by the app (e.g. "task_abc123_xyz").
-- Because tasks live inside a JSONB blob (not a relational table), the
-- cascade-on-delete of individual tasks is handled by the app; however,
-- deleting the *user* does cascade automatically via the auth.users FK.
--
-- How to run:
--   1. Open your Supabase project → SQL Editor.
--   2. Paste the contents of this file and click Run.
--   3. Confirm the table and policies appear under Table Editor / Auth policies.

-- 1. Long-description table (1:1 per user+task)
create table if not exists todo.task_descriptions (
  task_id   text        not null,
  user_id   uuid        not null references auth.users(id) on delete cascade,
  body      text        not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, task_id)
);

-- 2. Keep updated_at current on every update
create or replace function todo.set_task_descriptions_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_task_descriptions_updated_at on todo.task_descriptions;

create trigger trg_task_descriptions_updated_at
before update on todo.task_descriptions
for each row execute function todo.set_task_descriptions_updated_at();

-- 3. Row Level Security — users may only access their own rows
alter table todo.task_descriptions enable row level security;

drop policy if exists "Users can read own task descriptions"   on todo.task_descriptions;
drop policy if exists "Users can insert own task descriptions"  on todo.task_descriptions;
drop policy if exists "Users can update own task descriptions"  on todo.task_descriptions;
drop policy if exists "Users can delete own task descriptions"  on todo.task_descriptions;

create policy "Users can read own task descriptions"
  on todo.task_descriptions for select
  using (auth.uid() = user_id);

create policy "Users can insert own task descriptions"
  on todo.task_descriptions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own task descriptions"
  on todo.task_descriptions for update
  using (auth.uid() = user_id);

create policy "Users can delete own task descriptions"
  on todo.task_descriptions for delete
  using (auth.uid() = user_id);
