// Auto-generated by build.js — do not edit
const CACHE_VERSION = "1778074970398";
const CACHE_FILES = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js"
];
