// Auto-generated by build.js — do not edit
const CACHE_VERSION = "1779778492977";
const CACHE_FILES = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js"
];
